const fs = require('fs');

const translations = {
  EN: {
    "Découvrez notre objectif": "Discover our goal",
    "Notre": "Our",
    "Mission": "Mission",
    "Connecter les besoins aux meilleures compétences": "Connecting needs to the best skills",
    "Notre mission est de faciliter la rencontre entre les personnes à la recherche de services de qualité et les professionnels compétents capables d'y répondre.": "Our mission is to facilitate the meeting between people looking for quality services and competent professionals able to meet them.",
    "Dans un monde où il est parfois difficile de trouver le bon prestataire ou de faire connaître ses compétences, notre plateforme crée un pont simple, rapide et fiable entre les clients et les professionnels.": "In a world where it is sometimes difficult to find the right provider or make your skills known, our platform creates a simple, fast and reliable bridge between clients and professionals.",
    "Pourquoi existons-nous ?": "Why do we exist?",
    "Chaque jour, des milliers de personnes recherchent des solutions à leurs besoins :": "Every day, thousands of people look for solutions to their needs:",
    "Trouver un répétiteur pour accompagner un enfant.": "Find a tutor to support a child.",
    "Faire appel à un menuisier pour fabriquer un meuble.": "Call on a carpenter to make a piece of furniture.",
    "Recruter un développeur pour créer un site web.": "Recruit a developer to create a website.",
    "Trouver un électricien, un plombier ou un artisan qualifié.": "Find a qualified electrician, plumber or craftsman.",
    "Obtenir l'aide d'un professionnel de confiance pour un projet personnel ou professionnel.": "Get help from a trusted professional for a personal or professional project.",
    "Notre plateforme a été créée pour rendre ces recherches plus simples, plus rapides et plus efficaces.": "Our platform was created to make these searches simpler, faster and more efficient.",
    "Ce que nous apportons": "What we bring",
    "Pour les clients": "For clients",
    "Nous permettons aux utilisateurs de :": "We allow users to:",
    "Trouver facilement des professionnels qualifiés.": "Easily find qualified professionals.",
    "Comparer plusieurs prestataires.": "Compare several providers.",
    "Consulter les profils et les expériences.": "Consult profiles and experiences.",
    "Gagner du temps dans leurs recherches.": "Save time in their research.",
    "Réaliser leurs projets en toute confiance.": "Carry out their projects with confidence.",
    "Pour les professionnels": "For professionals",
    "Nous aidons les prestataires à :": "We help providers to:",
    "Mettre en valeur leurs compétences.": "Highlight their skills.",
    "Développer leur visibilité.": "Develop their visibility.",
    "Trouver de nouveaux clients.": "Find new clients.",
    "Développer leur activité.": "Develop their business.",
    "Construire leur réputation professionnelle.": "Build their professional reputation.",
    "Notre Vision": "Our Vision",
    "Nous souhaitons bâtir une communauté où le talent, le savoir-faire et le professionnalisme sont reconnus et accessibles à tous.": "We want to build a community where talent, know-how and professionalism are recognized and accessible to all.",
    "Nous croyons qu'en connectant les bonnes compétences aux bons besoins, nous contribuons à créer davantage d'opportunités, de confiance et de réussite pour chacun.": "We believe that by connecting the right skills to the right needs, we help create more opportunities, confidence and success for everyone.",
    "Nos engagements": "Our commitments",
    "Qualité dans les services proposés.": "Quality in the services offered.",
    "Compétence des professionnels présents sur la plateforme.": "Competence of the professionals present on the platform.",
    "Professionnalisme dans chaque interaction.": "Professionalism in every interaction.",
    "Transparence et confiance entre les utilisateurs.": "Transparency and trust between users.",
    "Innovation pour améliorer continuellement l'expérience.": "Innovation to continuously improve the experience.",
    "Notre Promesse": "Our Promise",
    "Transformer chaque besoin en opportunité et chaque compétence en solution.": "Transform every need into an opportunity and every skill into a solution.",
    "Qualité • Compétence • Professionnalisme": "Quality • Competence • Professionalism",
    "Au service de vos besoins.": "At the service of your needs.",
    "Retour à l'accueil": "Back to home"
  },
  ES: {
    "Découvrez notre objectif": "Descubre nuestro objetivo",
    "Notre": "Nuestra",
    "Mission": "Misión",
    "Connecter les besoins aux meilleures compétences": "Conectando necesidades a las mejores habilidades",
    "Notre mission est de faciliter la rencontre entre les personnes à la recherche de services de qualité et les professionnels compétents capables d'y répondre.": "Nuestra misión es facilitar el encuentro entre personas que buscan servicios de calidad y profesionales competentes capaces de responder a ellas.",
    "Dans un monde où il est parfois difficile de trouver le bon prestataire ou de faire connaître ses compétences, notre plateforme crée un pont simple, rapide et fiable entre les clients et les professionnels.": "En un mundo donde a veces es difícil encontrar el proveedor adecuado o dar a conocer sus talentos, nuestra plataforma crea un puente simple, rápido y confiable entre clientes y profesionales.",
    "Pourquoi existons-nous ?": "¿Por qué existimos?",
    "Chaque jour, des milliers de personnes recherchent des solutions à leurs besoins :": "Todos los días, miles de personas buscan soluciones a sus necesidades:",
    "Trouver un répétiteur pour accompagner un enfant.": "Encontrar un tutor para un niño.",
    "Faire appel à un menuisier pour fabriquer un meuble.": "Llamar a un carpintero para hacer un mueble.",
    "Recruter un développeur pour créer un site web.": "Reclutar a un desarrollador para crear un sitio web.",
    "Trouver un électricien, un plombier ou un artisan qualifié.": "Encontrar a un electricista, un fontanero o un artesano calificado.",
    "Obtenir l'aide d'un professionnel de confiance pour un projet personnel ou professionnel.": "Obtener ayuda de un profesional de confianza para un proyecto personal o profesional.",
    "Notre plateforme a été créée pour rendre ces recherches plus simples, plus rapides et plus efficaces.": "Nuestra plataforma fue creada para hacer estas búsquedas más simples, más rápidas y más efectivas.",
    "Ce que nous apportons": "Lo que aportamos",
    "Pour les clients": "Para los clientes",
    "Nous permettons aux utilisateurs de :": "Permitimos a los usuarios:",
    "Trouver facilement des professionnels qualifiés.": "Encontrar fácilmente profesionales calificados.",
    "Comparer plusieurs prestataires.": "Comparar varios proveedores.",
    "Consulter les profils et les expériences.": "Consultar perfiles y experiencias.",
    "Gagner du temps dans leurs recherches.": "Ahorrar tiempo en su investigación.",
    "Réaliser leurs projets en toute confiance.": "Realizar sus proyectos con confianza.",
    "Pour les professionnels": "Para los profesionales",
    "Nous aidons les prestataires à :": "Ayudamos a los proveedores a:",
    "Mettre en valeur leurs compétences.": "Destacar sus habilidades.",
    "Développer leur visibilité.": "Desarrollar su visibilidad.",
    "Trouver de nouveaux clients.": "Encontrar nuevos clientes.",
    "Développer leur activité.": "Desarrollar su negocio.",
    "Construire leur réputation professionnelle.": "Construir su reputación profesional.",
    "Notre Vision": "Nuestra Visión",
    "Nous souhaitons bâtir une communauté où le talent, le savoir-faire et le professionnalisme sont reconnus et accessibles à tous.": "Queremos construir una comunidad donde el talento, el conocimiento y el profesionalismo sean reconocidos y accesibles a todos.",
    "Nous croyons qu'en connectant les bonnes compétences aux bons besoins, nous contribuons à créer davantage d'opportunités, de confiance et de réussite pour chacun.": "Creemos que al conectar las habilidades adecuadas a las necesidades adecuadas, ayudamos a crear más oportunidades, confianza y éxito para todos.",
    "Nos engagements": "Nuestros compromisos",
    "Qualité dans les services proposés.": "Calidad en los servicios ofrecidos.",
    "Compétence des professionnels présents sur la plateforme.": "Competencia de los profesionales presentes en la plataforma.",
    "Professionnalisme dans chaque interaction.": "Profesionalismo en cada interacción.",
    "Transparence et confiance entre les utilisateurs.": "Transparencia y confianza entre usuarios.",
    "Innovation pour améliorer continuellement l'expérience.": "Innovación para mejorar continuamente la experiencia.",
    "Notre Promesse": "Nuestra Promesa",
    "Transformer chaque besoin en opportunité et chaque compétence en solution.": "Transformar cada necesidad en una oportunidad y cada habilidad en una solución.",
    "Qualité • Compétence • Professionnalisme": "Calidad • Competencia • Profesionalismo",
    "Au service de vos besoins.": "Al servicio de sus necesidades.",
    "Retour à l'accueil": "Volver al inicio"
  },
  DE: {
    "Découvrez notre objectif": "Entdecken Sie unser Ziel",
    "Notre": "Unsere",
    "Mission": "Mission",
    "Connecter les besoins aux meilleures compétences": "Bedürfnisse mit den besten Fähigkeiten verbinden",
    "Notre mission est de faciliter la rencontre entre les personnes à la recherche de services de qualité et les professionnels compétents capables d'y répondre.": "Unsere Mission ist es, die Begegnung zwischen Menschen, die hochwertige Dienstleistungen suchen, und kompetenten Fachleuten zu erleichtern.",
    "Dans un monde où il est parfois difficile de trouver le bon prestataire ou de faire connaître ses compétences, notre plateforme crée un pont simple, rapide et fiable entre les clients et les professionnels.": "In einer Welt, in der es manchmal schwierig ist, den richtigen Dienstleister zu finden oder seine Fähigkeiten bekannt zu machen, schafft unsere Plattform eine einfache, schnelle und zuverlässige Brücke zwischen Kunden und Fachleuten.",
    "Pourquoi existons-nous ?": "Warum existieren wir?",
    "Chaque jour, des milliers de personnes recherchent des solutions à leurs besoins :": "Jeden Tag suchen Tausende von Menschen nach Lösungen für ihre Bedürfnisse:",
    "Trouver un répétiteur pour accompagner un enfant.": "Einen Nachhilfelehrer finden, um ein Kind zu unterstützen.",
    "Faire appel à un menuisier pour fabriquer un meuble.": "Einen Tischler rufen, um ein Möbelstück herzustellen.",
    "Recruter un développeur pour créer un site web.": "Einen Entwickler rekrutieren, um eine Website zu erstellen.",
    "Trouver un électricien, un plombier ou un artisan qualifié.": "Einen qualifizierten Elektriker, Klempner oder Handwerker finden.",
    "Obtenir l'aide d'un professionnel de confiance pour un projet personnel ou professionnel.": "Hilfe von einem vertrauenswürdigen Fachmann für ein privates oder berufliches Projekt erhalten.",
    "Notre plateforme a été créée pour rendre ces recherches plus simples, plus rapides et plus efficaces.": "Unsere Plattform wurde mit dem doel erstellt, diese Suchen einfacher, schneller und effizienter zu machen.",
    "Ce que nous apportons": "Was wir bringen",
    "Pour les clients": "Für Kunden",
    "Nous permettons aux utilisateurs de :": "Wir ermöglichen Benutzern:",
    "Trouver facilement des professionnels qualifiés.": "Qualifizierte Fachleute leicht finden.",
    "Comparer plusieurs prestataires.": "Mehrere Anbieter vergleichen.",
    "Consulter les profils et les expériences.": "Profile und Erfahrungen konsultieren.",
    "Gagner du temps dans leurs recherches.": "Zeit bei der Suche sparen.",
    "Réaliser leurs projets en toute confiance.": "Ihre Projekte mit Zuversicht umsetzen.",
    "Pour les professionnels": "Für Fachleute",
    "Nous aidons les prestataires à :": "Wir helfen Anbietern bei:",
    "Mettre en valeur leurs compétences.": "Ihre Fähigkeiten hervorheben.",
    "Développer leur visibilité.": "Ihre Sichtbarkeit entwickeln.",
    "Trouver de nouveaux clients.": "Neue Kunden finden.",
    "Développer leur activité.": "Ihr Geschäft ausbauen.",
    "Construire leur réputation professionnelle.": "Ihren beruflichen Ruf aufbauen.",
    "Notre Vision": "Unsere Vision",
    "Nous souhaitons bâtir une communauté où le talent, le savoir-faire et le professionnalisme sont reconnus et accessibles à tous.": "Wir möchten eine Gemeinschaft aufbauen, in der Talent, Know-how und Professionalität anerkannt und für alle zugänglich sind.",
    "Nous croyons qu'en connectant les bonnes compétences aux bons besoins, nous contribuons à créer davantage d'opportunités, de confiance et de réussite pour chacun.": "Wir glauben, dass wir durch die Verbindung der richtigen Fähigkeiten mit den richtigen Bedürfnissen dazu beitragen, mehr Chancen, Vertrauen und Erfolg für alle zu schaffen.",
    "Nos engagements": "Unsere Verpflichtungen",
    "Qualité dans les services proposés.": "Qualität in den angebotenen Dienstleistungen.",
    "Compétence des professionnels présents sur la plateforme.": "Kompetenz der auf der Plattform anwesenden Fachleute.",
    "Professionnalisme dans chaque interaction.": "Professionalität in jeder Interaktion.",
    "Transparence et confiance entre les utilisateurs.": "Transparenz und Vertrauen zwischen Benutzern.",
    "Innovation pour améliorer continuellement l'expérience.": "Innovation, um die Erfahrung kontinuierlich zu verbessern.",
    "Notre Promesse": "Unser Versprechen",
    "Transformer chaque besoin en opportunité et chaque compétence en solution.": "Jedes Bedürfnis in eine Chance und jede Fähigkeit in eine Lösung verwandeln.",
    "Qualité • Compétence • Professionnalisme": "Qualität • Kompetenz • Professionalität",
    "Au service de vos besoins.": "Im Dienste Ihrer Bedürfnisse.",
    "Retour à l'accueil": "Zurück zur Startseite"
  },
  IT: {
    "Découvrez notre objectif": "Scopri il nostro obiettivo",
    "Notre": "La nostra",
    "Mission": "Missione",
    "Connecter les besoins aux meilleures compétences": "Connettere i bisogni alle migliori competenze",
    "Notre mission est de faciliter la rencontre entre les personnes à la recherche de services de qualité et les professionnels compétents capables d'y répondre.": "La nostra missione è facilitare lincontro tra le persone alla ricerca di servizi di qualità e i professionisti competenti in grado di rispondergli.",
    "Dans un monde où il est parfois difficile de trouver le bon prestataire ou de faire connaître ses compétences, notre plateforme crée un pont simple, rapide et fiable entre les clients et les professionnels.": "In un mondo in cui a volte è difficile trovare il fornitore giusto o far conoscere le proprie competenze, la nostra piattaforma crea un ponte semplice, rapido e affidabile tra clienti e professionisti.",
    "Pourquoi existons-nous ?": "Perché esistiamo?",
    "Chaque jour, des milliers de personnes recherchent des solutions à leurs besoins :": "Ogni giorno, migliaia di persone cercano soluzioni ai loro bisogni:",
    "Trouver un répétiteur pour accompagner un enfant.": "Trovare un tutor per accompagnare un bambino.",
    "Faire appel à un menuisier pour fabriquer un meuble.": "Chiamare un falegname per costruire un mobile.",
    "Recruter un développeur pour créer un site web.": "Reclutare un programmatore per creare un sito web.",
    "Trouver un électricien, un plombier ou un artisan qualifié.": "Trovare un elettricista, un idraulico o un artigiano qualificato.",
    "Obtenir l'aide d'un professionnel de confiance pour un projet personnel ou professionnel.": "Ottenere laiuto di un professionista di fiducia per un progetto personale o professionale.",
    "Notre plateforme a été créée pour rendre ces recherches plus simple, plus rapidi e plus efficaci.": "La nostra piattaforma è stata creata per rendere queste ricerche più semplici, più rapide e più efficaci.",
    "Notre plateforme a été créée pour rendre ces recherches plus simples, plus rapides et plus efficaces.": "La nostra piattaforma è stata creata per rendere queste ricerche più semplici, più rapide e più efficaci.",
    "Ce que nous apportons": "Cosa portiamo",
    "Pour les clients": "Per i clienti",
    "Nous permettons aux utilisateurs de :": "Consentiamo agli utenti di:",
    "Trouver facilement des professionnels qualifiés.": "Trovare facilmente professionisti qualificati.",
    "Comparer plusieurs prestataires.": "Confrontare più fornitori.",
    "Consulter les profils et les expériences.": "Consultare profili ed esperienze.",
    "Gagner du temps dans leurs recherches.": "Risparmiare tempo nelle loro ricerche.",
    "Réaliser leurs projets en toute confiance.": "Realizzare i loro progetti con fiducia.",
    "Pour les professionnels": "Per i professionisti",
    "Nous aidons les prestataires à :": "Aiutiamo i fornitori a:",
    "Mettre en valeur leurs compétences.": "Evidenziare le loro competenze.",
    "Développer leur visibilité.": "Sviluppare la loro visibilità.",
    "Trouver de nouveaux clients.": "Trovare nuovi clienti.",
    "Développer leur activité.": "Sviluppare la loro attività.",
    "Construire leur réputation professionnelle.": "Costruire la loro reputazione professionale.",
    "Notre Vision": "La nostra Visione",
    "Nous souhaitons bâtir une communauté où le talent, le savoir-faire et le professionnalisme sont reconnus et accessibles à tous.": "Desideriamo costruire una comunità in cui talento, know-how e professionalità siano riconosciuti e accessibili a tutti.",
    "Nous croyons qu'en connectant les bonnes compétences aux bons besoins, nous contribuons à créer davantage d'opportunités, de confiance et de réussite pour chacun.": "Crediamo che collegando le competenze giuste ai bisogni giusti, contribuiamo a creare maggiori opportunità, fiducia e successo per tutti.",
    "Nos engagements": "I nostri impegni",
    "Qualité dans les services proposés.": "Qualità nei servizi offerti.",
    "Compétence des professionnels présents sur la plateforme.": "Competenza dei professionisti presenti sulla piattaforma.",
    "Professionnalisme dans chaque interaction.": "Professionalità in ogni interazione.",
    "Transparence et confiance entre les utilisateurs.": "Trasparenza e fiducia tra gli utenti.",
    "Innovation pour améliorer continuellement l'expérience.": "Innovazione per migliorare continuamente lesperienza.",
    "Notre Promesse": "La nostra Promessa",
    "Transformer chaque besoin en opportunité et chaque compétence en solution.": "Trasformare ogni bisogno in unopportunità e ogni competenza in una soluzione.",
    "Qualité • Compétence • Professionnalisme": "Qualità • Competenza • Professionalità",
    "Au service de vos besoins.": "Al servizio dei tuoi bisogni.",
    "Retour à l'accueil": "Torna alla home"
  },
  PT: {
    "Découvrez notre objectif": "Descubra o nosso objetivo",
    "Notre": "Nossa",
    "Mission": "Missão",
    "Connecter les besoins aux meilleures compétences": "Conectando necessidades às melhores habilidades",
    "Notre mission est de faciliter la rencontre entre les personnes à la recherche de services de qualité et les professionnels compétents capables d'y répondre.": "Nossa missão é facilitar o encontro entre pessoas que buscam serviços de qualidade e os profissionais competentes capazes de respondê-las.",
    "Dans un monde où il est parfois difficile de trouver le bon prestataire ou de faire connaître ses compétences, notre plateforme crée un pont simple, rapide et fiable entre les clients et les professionnels.": "Em um mundo onde às vezes é difícil encontrar o fornecedor certo ou divulgar suas habilidades, nossa plataforma cria uma ponte simples, rápida e confiável entre clientes e profissionais.",
    "Pourquoi existons-nous ?": "Por que existimos?",
    "Chaque jour, des milliers de personnes recherchent des solutions à leurs besoins :": "Todos os dias, milhares de pessoas buscam soluções para suas necessidades:",
    "Trouver un répétiteur pour accompagner un enfant.": "Encontrar um tutor para acompanhar uma criança.",
    "Faire appel à un menuisier pour fabriquer un meuble.": "Chamar um carpinteiro para construir um móvel.",
    "Recruter un développeur pour créer un site web.": "Recrutar um desenvolvedor para criar um site.",
    "Trouver un électricien, un plombier ou un artisan qualifié.": "Encontrar um eletricista, encanador ou artesão qualificado.",
    "Obtenir l'aide d'un professionnel de confiance pour un projet personnel ou professionnel.": "Obter a ajuda de um profissional de confiança para um projeto pessoal ou profissional.",
    "Notre plateforme a été créée pour rendre ces recherches plus simples, plus rapides et plus efficaces.": "Nossa plataforma foi criada para tornar essas buscas mais simples, rápidas e eficientes.",
    "Ce que nous apportons": "O que trazemos",
    "Pour les clients": "Para os clientes",
    "Nous permettons aux utilisateurs de :": "Permitimos que os usuários:",
    "Trouver facilement des professionnels qualifiés.": "Encontrem facilmente profissionais qualificados.",
    "Comparer plusieurs prestataires.": "Comparem vários fornecedores.",
    "Consulter les profils et les expériences.": "Consultem perfis e experiências.",
    "Gagner du temps dans leurs recherches.": "Economizem tempo em suas pesquisas.",
    "Réaliser leurs projets en toute confiance.": "Realizem seus projetos com confiança.",
    "Pour les professionnels": "Para os profissionais",
    "Nous aidons les prestataires à :": "Ajudamos os fornecedores a:",
    "Mettre en valeur leurs compétences.": "Destacar suas habilidades.",
    "Développer leur visibilité.": "Desenvolver sua visibilidade.",
    "Trouver de nouveaux clients.": "Encontrar novos clientes.",
    "Développer leur activité.": "Desenvolver o seu negócio.",
    "Construire leur réputation professionnelle.": "Construir sua reputação profissional.",
    "Notre Vision": "Nossa Visão",
    "Nous souhaitons bâtir une communauté où le talent, le savoir-faire et le professionnalisme sont reconnus et accessibles à tous.": "Queremos construir uma comunidade onde talento, know-how e profissionalismo sejam reconhecidos e acessíveis a todos.",
    "Nous croyons qu'en connectant les bonnes compétences aux bons besoins, nous contribuons à créer davantage d'opportunités, de confiance et de réussite pour chacun.": "Acreditamos que conectando as habilidades certas às necessidades certas, ajudamos a criar mais oportunidades, confiança e sucesso para todos.",
    "Nos engagements": "Nossos compromissos",
    "Qualité dans les services proposés.": "Qualidade nos serviços prestados.",
    "Compétence des professionnels présents sur la plateforme.": "Competência dos profissionais presentes na plataforma.",
    "Professionnalisme dans chaque interaction.": "Profissionalismo em cada interação.",
    "Transparence et confiance entre les utilisateurs.": "Transparência e confiança entre os usuários.",
    "Innovation pour améliorer continuellement l'expérience.": "Inovação para melhorar continuamente a experiência.",
    "Notre Promesse": "Nossa Promessa",
    "Transformer chaque besoin en opportunité et chaque compétence en solution.": "Transformar cada necessidade em uma oportunidade e cada habilidade em uma solução.",
    "Qualité • Compétence • Professionnalisme": "Qualidade • Competência • Profissionalismo",
    "Au service de vos besoins.": "A serviço de suas necessidades.",
    "Retour à l'accueil": "Voltar à página inicial"
  },
  AR: {
    "Découvrez notre objectif": "اكتشف هدفنا",
    "Notre": "مهمتنا",
    "Mission": "المهمة",
    "Connecter les besoins aux meilleures compétences": "ربط الاحتياجات بأفضل المهارات",
    "Notre mission est de faciliter la rencontre entre les personnes à la recherche de services de qualité et les professionnels compétents capables d'y répondre.": "مهمتنا هي تسهيل اللقاء بين الأشخاص الذين يبحثون عن خدمات عالية الجودة والمهنيين الأكفاء القادرين على الرد عليها.",
    "Dans un monde où il est parfois difficile de trouver le bon prestataire ou de faire connaître ses compétences, notre plateforme crée un pont simple, rapide et fiable entre les clients et les professionnels.": "في عالم يكون فيه من الصعب أحيانا العثور على مزود الخدمة المناسب أو التعريف بمهاراتهم، تخلق منصتنا جسرا بسيطا وسريعا وموثوقا بين العملاء والمهنيين.",
    "Pourquoi existons-nous ?": "لماذا نحن موجودون؟",
    "Chaque jour, des milliers de personnes recherchent des solutions à leurs besoins :": "كل يوم، يبحث آلاف الأشخاص عن حلول لاحتياجاتهم:",
    "Trouver un répétiteur pour accompagner un enfant.": "إيجاد مدرس لدعم الطفل.",
    "Faire appel à un menuisier pour fabriquer un meuble.": "استدعاء نجار لصنع قطعة أثاث.",
    "Recruter un développeur pour créer un site web.": "توظيف مطور لإنشاء موقع ويب.",
    "Trouver un électricien, un plombier ou un artisan qualifié.": "العثور على كهربائي، سباك أو حرفي مؤهل.",
    "Obtenir l'aide d'un professionnel de confiance pour un projet personnel ou professionnel.": "الحصول على المساعدة من محترف موثوق به لمشروع شخصي أو مهني.",
    "Notre plateforme a été créée pour rendre ces recherches plus simples, plus rapides et plus efficaces.": "تم إنشاء منصتنا لجعل هذه العمليات أبسط وأسرع وأكثر كفاءة.",
    "Ce que nous apportons": "ما نقدمه",
    "Pour les clients": "للعملاء",
    "Nous permettons aux utilisateurs de :": "نسمح للمستخدمين بتنفيذ ما يلي:",
    "Trouver facilement des professionnels qualifiés.": "العثور بسهولة على المهنيين المؤهلين.",
    "Comparer plusieurs prestataires.": "مقارنة العديد من مزودي الخدمة.",
    "Consulter les profils et les expériences.": "استشارة ملفات التعريف والتجارب.",
    "Gagner du temps dans leurs recherches.": "توفير الوقت في أبحاثهم.",
    "Réaliser leurs projets en toute confiance.": "القيام بمشاريعهم بثقة.",
    "Pour les professionnels": "للمهنيين",
    "Nous aidons les prestataires à :": "نساعد مزودي الخدمة على:",
    "Mettre en valeur leurs compétences.": "إبراز مهاراتهم.",
    "Développer leur visibilité.": "تطوير رؤيتهم.",
    "Trouver de nouveaux clients.": "العثور على عملاء جدد.",
    "Développer leur activité.": "تطوير أعمالهم.",
    "Construire leur réputation professionnelle.": "بناء سمعتهم المهنية.",
    "Notre Vision": "رؤيتنا",
    "Nous souhaitons bâtir une communauté où le talent, le savoir-faire et le professionnalisme sont reconnus et accessibles à tous.": "نرغب في بناء مجتمع حيث الموهبة والدراية والاحتراف معترف بها ومتاحة للجميع.",
    "Nous croyons qu'en connectant les bonnes compétences aux bons besoins, nous contribuons à créer davantage d'opportunités, de confiance et de réussite pour chacun.": "نحن نؤمن بأنه من خلال ربط المهارات المناسبة بالاحتياجات المناسبة ، نساهم في إنشاء المزيد من الفرص والثقة والنجاح للجميع.",
    "Nos engagements": "التزاماتنا",
    "Qualité dans les services proposés.": "الجودة في الخدمات المقدمة.",
    "Compétence des professionnels présents sur la plateforme.": "كفاءة المهنيين الموجودين على المنصة.",
    "Professionnalisme dans chaque interaction.": "احترافية في كل تفاعل.",
    "Transparence et confiance entre les utilisateurs.": "الشفافية والثقة بين المستخدمين.",
    "Innovation pour améliorer continuellement l'expérience.": "الابتكار لتحسين التجربة باستمرار.",
    "Notre Promesse": "وعدنا",
    "Transformer chaque besoin en opportunité et chaque compétence en solution.": "تحويل كل حاجة إلى فرصة وكل مهارة إلى حل.",
    "Qualité • Compétence • Professionnalisme": "الجودة • الكفاءة • المهنية",
    "Au service de vos besoins.": "في خدمة احتياجاتك.",
    "Retour à l'accueil": "العودة إلى الصفحة الرئيسية"
  },
  ZH: {
    "Découvrez notre objectif": "发现我们的目标",
    "Notre": "我们的",
    "Mission": "使命",
    "Connecter les besoins aux meilleures compétences": "将需求与最佳技能联系起来",
    "Notre mission est de faciliter la rencontre entre les personnes à la recherche de services de qualité et les professionnels compétents capables d'y répondre.": "我们的任务是帮助寻找高质量服务的人和能够响应他们能力的专业人士会面。",
    "Dans un monde où il est parfois difficile de trouver le bon prestataire ou de faire connaître ses compétences, notre plateforme crée un pont simple, rapide et fiable entre les clients et les professionnels.": "在一个很难找到合适的服务提供商或宣传您的技能的世界中，我们的平台在客户和专业人士之间建立了简单、快速和可靠的桥梁。",
    "Pourquoi existons-nous ?": "我们为何存在？",
    "Chaque jour, des milliers de personnes recherchent des solutions à leurs besoins :": "每天，成千上万的人在寻找满足其需求的解决方案：",
    "Trouver un répétiteur pour accompagner un enfant.": "寻找导师来陪伴孩子。",
    "Faire appel à un menuisier pour fabriquer un meuble.": "找木匠做一件家具。",
    "Recruter un développeur pour créer un site web.": "招聘开发人员来创建网站。",
    "Trouver un électricien, un plombier ou un artisan qualifié.": "找一位有执照的电工、水管工或工匠。",
    "Obtenir l'aide d'un professionnel de confiance pour un projet personnel ou professionnel.": "让值得信赖的专业人员帮助进行个人或专业项目。",
    "Notre plateforme a été créée pour rendre ces recherches plus simples, plus rapides et plus efficaces.": "创建我们平台的目的是使搜索变得更加简单、快速和高效。",
    "Ce que nous apportons": "我们带来了什么",
    "Pour les clients": "对于客户",
    "Nous permettons aux utilisateurs de :": "我们允许用户进行以下操作：",
    "Trouver facilement des professionnels qualifiés.": "轻松找到合格的专业人员。",
    "Comparer plusieurs prestataires.": "比较几个服务提供商。",
    "Consulter les profils et les expériences.": "查看个人资料和经验。",
    "Gagner du temps dans leurs recherches.": "节省搜索时间。",
    "Réaliser leurs projets en toute confiance.": "充满信心地执行他们的项目。",
    "Pour les professionnels": "对于专业人士",
    "Nous aidons les prestataires à :": "我们帮助提供商：",
    "Mettre en valeur leurs compétences.": "突出他们的技能。",
    "Développer leur visibilité.": "扩大知名度。",
    "Trouver de nouveaux clients.": "寻找新客户。",
    "Développer leur activité.": "拓展业务。",
    "Construire leur réputation professionnelle.": "建立职业声誉。",
    "Notre Vision": "我们的愿景",
    "Nous souhaitons bâtir une communauté où le talent, le savoir-faire et le professionnalisme sont reconnus et accessibles à tous.": "我们希望建立一个让每个人的才华、专业知识和专业精神都得到认可和获取的社区。",
    "Nous croyons qu'en connectant les bonnes compétences aux bons besoins, nous contribuons à créer davantage d'opportunités, de confiance et de réussite pour chacun.": "我们相信，通过将合适的技能与合适的需求联系起来，我们可以为每个人创造更多的机会、信心和成功。",
    "Nos engagements": "我们的承诺",
    "Qualité dans les services proposés.": "所提供服务的质量。",
    "Compétence des professionnels présents sur la plateforme.": "平台上展示的专业人员的能力。",
    "Professionnalisme dans chaque interaction.": "每次互动中的专业精神。",
    "Transparence et confiance entre les utilisateurs.": "用户之间的透明度和信任。",
    "Innovation pour améliorer continuellement l'expérience.": "创新以持续改进体验。",
    "Notre Promesse": "我们的承诺",
    "Transformer chaque besoin en opportunité et chaque compétence en solution.": "把每个需求变成机会，把每一项技能都变成解决方案。",
    "Qualité • Compétence • Professionnalisme": "质量 • 胜任能力 • 专业精神",
    "Au service de vos besoins.": "服务于您的需求。",
    "Retour à l'accueil": "返回首页"
  }
};

let code = fs.readFileSync('src/i18n.ts', 'utf8');

for (const lang of ['EN', 'ES', 'DE', 'IT', 'PT', 'AR', 'ZH']) {
    const regex = new RegExp(lang + ':\\s*\\{\\s*translation:\\s*\\{([\\s\\S]*?)\\}\\s*\\}', 'm');
    const match = code.match(regex);
    if(match) {
        let block = match[1];
        let newContent = "";
        for (const [key, val] of Object.entries(translations[lang])) {
           if (!block.includes('"' + key + '":')) {
               newContent += '      "' + key + '": "' + val.replace(/"/g, '\\"') + '",\n';
           }
        }
        code = code.replace(match[0], match[0].replace(match[1], match[1] + newContent));
    }
}
fs.writeFileSync('src/i18n.ts', code, 'utf8');
console.log('Successfully injected translations for all languages.');
