const fs = require('fs');

const heroDescriptions = {
  sport: ["Atteignez vos objectifs physiques avec l'accompagnement personnalisé de nos entraîneurs passionnés.", "Reach your physical goals with personalized guidance from our passionate trainers.", "Alcanza tus objetivos físicos con la orientación personalizada de nuestros entrenadores apasionados.", "Erreichen Sie Ihre körperlichen Ziele mit persönlicher Anleitung durch unsere leidenschaftlichen Trainer.", "Raggiungi i tuoi obiettivi fisici con una guida personalizzata dai nostri allenatori appassionati.", "Alcance seus objetivos físicos com orientação personalizada de nossos treinadores apaixonados.", "حقق أهدافك البدنية من خلال إرشادات مخصصة من مدربينا الشغوفين.", "在我们充满热情的教练的个性化指导下实现您的身体目标。"],
  security: ["Assurez la sécurité de vos biens et événements avec des professionnels formés et qualifiés.", "Ensure the security of your property and events with trained and qualified professionals.", "Garantiza la seguridad de tus propiedades y eventos con profesionales capacitados y calificados.", "Sorgen Sie mit geschulten und qualifizierten Fachleuten für die Sicherheit Ihres Eigentums und Ihrer Veranstaltungen.", "Garantisci la sicurezza delle tue proprietà e degli eventi con professionisti preparati e qualificati.", "Garanta a segurança de sua propriedade e eventos com profissionais treinados e qualificados.", "ضمان أمن ممتلكاتك وفعالياتك مع محترفين مدربين ومؤهلين.", "由受过培训和合格的专业人员确保您财产和活动的安全。"],
  translator: ["Facilitez vos échanges internationaux grâce à nos experts en traduction et interprétation.", "Facilitate your international exchanges with our translation and interpretation experts.", "Facilita tus intercambios internacionales con nuestros expertos en traducción e interpretación.", "Erleichtern Sie Ihre internationalen Austausche mit unseren Übersetzungs- und Dolmetscherexperten.", "Facilita i tuoi scambi internazionali con i nostri esperti di traduzione e interpretazione.", "Facilite seus intercâmbios internacionais com nossos especialistas em tradução e interpretação.", "تسهيل تبادلاتك الدولية مع خبرائنا في الترجمة والترجمة الفورية.", "通过我们的笔译和口译专家促进您的国际交流。"],
  carpenter: ["Des artisans qualifiés pour tous vos travaux de menuiserie, de la fabrication à la rénovation.", "Qualified artisans for all your carpentry work, from manufacturing to renovation.", "Artesanos cualificados para todos tus trabajos de carpintería, desde la fabricación hasta la renovación.", "Qualifizierte Handwerker für all Ihre Tischlerarbeiten, von der Herstellung bis zur Renovierung.", "Artigiani qualificati per tutti i tuoi lavori di falegnameria, dalla produzione alla ristrutturazione.", "Artesãos qualificados para todo o seu trabalho de carpintaria, da fabricação à renovação.", "حرفيون مؤهلون لجميع أعمال النجارة الخاصة بك، من التصنيع إلى التجديد.", "为您的所有木工作业（从制造到翻新）提供合格的工匠。"],
  decorator: ["Sublimez votre intérieur avec l'expertise de nos décorateurs d'intérieur passionnés.", "Enhance your interior with the expertise of our passionate interior decorators.", "Mejora tu interior con la experiencia de nuestros apasionados decoradores de interiores.", "Werten Sie Ihr Interieur mit der Expertise unserer leidenschaftlichen Innenarchitekten auf.", "Migliora i tuoi interni con l'esperienza dei nostri appassionati decoratori d'interni.", "Aprimore seu interior com a experiência de nossos apaixonados decoradores de interiores.", "تحسين الديكور الداخلي الخاص بك مع خبرة مصممي الديكور الداخلي المتحمسين لدينا.", "通过我们充满热情的室内装饰专家的专业知识提升您的室内环境。"],
  mechanic: ["Réparez et entretenez votre véhicule avec nos experts en mécanique automobile.", "Repair and maintain your vehicle with our auto mechanics experts.", "Repara y mantén tu vehículo con nuestros expertos en mecánica automotriz.", "Reparieren und warten Sie Ihr Fahrzeug mit unseren Kfz-Mechaniker-Experten.", "Ripara e mantieni il tuo veicolo con i nostri esperti di meccanica automobilistica.", "Repare e faça a manutenção do seu veículo com os nossos especialistas em mecânica automóvel.", "إصلاح وصيانة سيارتك مع خبرائنا في ميكانيكا السيارات.", "与我们的汽车机械专家一起维修和保养您的车辆。"],
  garden: ["Transformez et entretenez vos espaces verts grâce à l'expertise de nos jardiniers et paysagistes passionnés.", "Transform and maintain your green spaces with the expertise of our passionate gardeners and landscapers.", "Transforma y mantén tus espacios verdes con la experiencia de nuestros apasionados jardineros y paisajistas.", "Verwandeln und pflegen Sie Ihre Grünflächen mit der Expertise unserer leidenschaftlichen Gärtner und Landschaftsgestalter.", "Trasforma e mantieni i tuoi spazi verdi con l'esperienza dei nostri appassionati giardinieri e paesaggisti.", "Transforme e mantenha os seus espaços verdes com a experiência dos nossos apaixonados jardineiros e paisagistas.", "تحويل وتطوير المساحات الخضراء الخاصة بك بفضل خبرات البستانيين ومنسقي الحدائق الشغوفين لدينا.", "通过我们热情的园丁和景观规划师的专业技能，改造和维护您的绿地空间。"],
  cooking: ["Offrez-vous un moment gastronomique avec des chefs talentueux, de la préparation de repas aux événements privés.", "Treat yourself to a gastronomic moment with talented chefs, from meal preparation to private events.", "Regálate un momento gastronómico con talentosos chefs, desde la preparación de comidas hasta eventos privados.", "Gönnen Sie sich einen gastronomischen Moment mit talentierten Köchen, von der Zubereitung von Mahlzeiten bis hin zu privaten Veranstaltungen.", "Concediti un momento gastronomico con chef talentuosi, dalla preparazione dei pasti agli eventi privati.", "Mime-se com um momento gastronômico com chefs talentosos, da preparação de refeições a eventos privados.", "كافئ نفسك بلحظة لتذوق الطعام مع طهاة موهوبين، بدءًا من إعداد الوجبات وحتى الفعاليات الخاصة.", "从膳食准备到私人活动，让自己与才华横溢的主厨共享美食时光。"],
  services: ["Trouvez les meilleurs experts pour vos travaux du quotidien, sélectionnés avec soin et prêts à intervenir rapidement.", "Find the best experts for your daily tasks, carefully selected and ready to intervene quickly.", "Encuentra a los mejores expertos para tus tareas diarias, cuidadosamente seleccionados y listos para intervenir rápidamente.", "Finden Sie die besten Experten für Ihre täglichen Aufgaben, sorgfältig ausgewählt und bereit für ein schnelles Eingreifen.", "Trova i migliori esperti per i tuoi lavori quotidiani, accuratamente selezionati e pronti a intervenire rapidamente.", "Encontre os melhores especialistas para o seu trabalho diário, cuidadosamente selecionados e prontos para intervir rapidamente.", "اعثر على أفضل الخبراء لمهامك اليومية، تم اختيارهم بعناية ومستعدون للتدخل السريع.", "寻找最适合您日常任务的专家，经过精心挑选并随时准备迅速干预。"],
  tech: ["Développeurs, designers et marketeurs de talent pour propulser vos projets numériques vers de nouveaux sommets.", "Talented developers, designers, and marketers to propel your digital projects to new heights.", "Talentosos desarrolladores, diseñadores y especialistas en marketing para impulsar tus proyectos digitales a nuevas alturas.", "Talentierte Entwickler, Designer und Vermarkter, um Ihre digitalen Projekte auf ein neues Niveau zu heben.", "Sviluppatori, designer e operatori di marketing di talento per proiettare i tuoi progetti digitali verso nuovi traguardi.", "Desenvolvedores, designers e profissionais de marketing talentosos para impulsionar seus projetos digitais para novos patamares.", "مطورون ومصممون ومسوقون موهوبون لدفع مشاريعك الرقمية إلى آفاق جديدة.", "才华横溢的开发人员、设计师和营销人员，将您的数字项目推向新高度。"],
  repair: ["Un savoir-faire reconnu pour toutes vos rénovations et réparations, avec des professionnels de confiance à vos côtés.", "Recognized expertise for all your renovations and repairs, with trusted professionals by your side.", "Experiencia reconocida para todas tus renovaciones y reparaciones, con profesionales de confianza a tu lado.", "Anerkannte Fachkenntnisse für alle Ihre Renovierungen und Reparaturen, mit vertrauenswürdigen Fachleuten an Ihrer Seite.", "Competenza riconosciuta per tutte le tue ristrutturazioni e riparazioni, con professionisti di fiducia al tuo fianco.", "Um know-how reconhecido para todas as suas renovações e reparações, com profissionais de confiança ao seu lado.", "خبرة معترف بها في جميع أعمال التجديد والإصلاحات الخاصة بك، مع محترفين موثوقين بجانبك.", "您的所有翻新和维修工作均受备受信赖的技术专家的认可，并有可信赖的专业人员在您身边。"],
  photo: ["Capturez vos événements précieux avec l'expertise de nos photographes professionnels prêts à sublimer chaque instant.", "Capture your precious events with the expertise of our professional photographers ready to sublime every moment.", "Captura tus eventos preciosos con la experiencia de nuestros fotógrafos profesionales listos para sublimar cada momento.", "Halten Sie Ihre wertvollen Ereignisse mit der Expertise unserer professionellen Fotografen fest, die jeden Moment veredeln.", "Cattura i tuoi eventi preziosi con l'esperienza dei nostri fotografi professionisti pronti a sublimare ogni momento.", "Capture seus eventos preciosos com a expertise dos nossos fotógrafos profissionais prontos a sublimar cada momento.", "التقط أحداثك الثمينة مع خبرات مصورينا المحترفين المستعدين لترقية كل لحظة.", "捕捉您珍贵的赛事，借助我们专业的摄影师的专业知识，随时升华每一个瞬间。"],
  transport: ["Déplacez-vous facilement et en toute sécurité avec nos chauffeurs professionnels qualifiés.", "Move easily and safely with our qualified professional drivers.", "Muévete fácilmente y con seguridad con nuestros conductores profesionales cualificados.", "Bewegen Sie sich einfach und sicher mit unseren qualifizierten professionellen Fahrern.", "Spostati facilmente in totale sicurezza con i nostri autisti professionisti qualificati.", "Desloque-se de forma fácil e segura com os nossos motoristas profissionais qualificados.", "تنقل بسهولة وأمان تامة مع سائقينا المهنيين المؤهلين.", "借助我们合格的专业司机轻松安全地移动。"],
  moving: ["Déménagez l'esprit tranquille avec nos experts du transport, efficaces et précautionneux.", "Move with peace of mind with our transport experts, efficient and careful.", "Múdate con tranquilidad con nuestros expertos en transporte, eficientes y cuidadosos.", "Ziehen Sie mit unseren Transportexperten beruhigt, effizient und sorgfältig um.", "Trasloco tranquillo con i nostri esperti dei trasporti, efficienti e attenti.", "Mude com tranquilidade com nossos especialistas de transporte, eficientes e cuidadosos.", "تحرك بكل راحة بال مع خبرائنا في النقل، فاعلون وحذرون.", "在我们的高效且仔细的运输专家协助下安心搬家。"],
  education: ["Développez de nouvelles compétences avec des professeurs passionnés, en ligne ou à domicile, selon vos besoins.", "Develop new skills with passionate teachers, online or at home, depending on your needs.", "Desarrolla nuevas habilidades con profesores apasionados, en línea o en casa, según tus necesidades.", "Entwickeln Sie neue Fähigkeiten mit leidenschaftlichen Lehrern, online oder zu Hause, je nach Ihren Bedürfnissen.", "Sviluppare nuove competenze con insegnanti appassionati, online o al proprio domicilio, secondo le proprie esigenze.", "Desenvolva novas valências com os nossos professores apaixonados, de forma online ou em casa, de acordo com as tuas necessidades.", "تطوير مهارات جديدة مع معلمين متحمسين، أون لاين أو في المنزل، وفقًا لاحتياجاتك.", "通过充满热情的老师在线或根据您的需要在家学习新技能。"]
};

const langs = ['FR', 'EN', 'ES', 'DE', 'IT', 'PT', 'AR', 'ZH'];
let content = fs.readFileSync('src/i18n.ts', 'utf8');

langs.forEach((lang, index) => {
  const translationsToInsert = Object.keys(heroDescriptions).reduce((acc, key) => {
    acc[`hero.desc.${key}`] = heroDescriptions[key][index];
    return acc;
  }, {});

  const regex = new RegExp(`(${lang}:\\s*\\{\\s*translation:\\s*\\{)([\\s\\S]*?)(\\}\\s*\\})`);
  content = content.replace(regex, (match, prefix, translationKeys, suffix) => {
    let replacedText = translationKeys;
    for (const [key, value] of Object.entries(translationsToInsert)) {
      const k = JSON.stringify(key);
      const v = JSON.stringify(value);
      if (!replacedText.includes(k + ":")) {
        replacedText += `      ${k}: ${v},\n`;
      }
    }
    return prefix + replacedText + suffix;
  });
});

fs.writeFileSync('src/i18n.ts', content, 'utf8');
